"""
Typed request and response models for SkillForge AI Career Chatbot.
Post-MVP Phase 2, Checkpoint P2-C.

Strict architectural boundary:
    "The LLM never decides what is true."
    "Deterministic systems decide what is true.
     AI explains, reasons over, and personalizes verified evidence."

All models enforce deep immutability (frozen=True, extra='forbid') and
strictly avoid untyped dictionaries (Dict[str, Any]).
"""

from enum import Enum
from typing import Any, Optional, Tuple
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.ai.context.models import VerifiedContext
from app.rag.models import RAGRetrievalResult


class ChatResponseStatus(str, Enum):
    """Status indicating the grounding nature of the chatbot response."""
    EXPLANATORY = "EXPLANATORY"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class ChatUsageStats(BaseModel):
    """
    Strongly-typed execution and token telemetry from local Qwen inference.
    Replaces untyped dictionaries with explicit metric fields.
    """
    total_duration: Optional[int] = Field(None, ge=0, description="Total execution duration in nanoseconds")
    load_duration: Optional[int] = Field(None, ge=0, description="Model load duration in nanoseconds")
    prompt_eval_count: Optional[int] = Field(None, ge=0, description="Tokens evaluated in prompt context")
    eval_count: Optional[int] = Field(None, ge=0, description="Tokens generated in explanation")

    model_config = ConfigDict(frozen=True, extra="forbid")


class CareerChatRequest(BaseModel):
    """
    Typed request envelope for the evidence-grounded career chatbot.
    Requires an already-constructed and validated VerifiedContext instance.
    Arbitrary system instructions, unverified facts, and untyped dictionaries are forbidden.
    """
    verified_context: VerifiedContext = Field(
        ...,
        description="Pre-validated immutable container of deterministic SkillForge facts",
    )
    user_query: str = Field(
        ...,
        min_length=1,
        max_length=1000,
        description="Candidate question regarding their verified career facts",
    )
    max_tokens: int = Field(
        1024,
        ge=1,
        le=4096,
        description="Maximum generation token budget",
    )
    temperature: float = Field(
        0.2,
        ge=0.0,
        le=1.0,
        description="Generation temperature for deterministic explanation",
    )

    model_config = ConfigDict(frozen=True, extra="forbid")

    @field_validator("verified_context")
    @classmethod
    def validate_verified_context_instance(cls, v: Any) -> VerifiedContext:
        if not isinstance(v, VerifiedContext):
            raise ValueError("verified_context must be an actual VerifiedContext instance, not an arbitrary dictionary.")
        from app.ai.context.validation import validate_verified_context
        validate_verified_context(v)
        return v

    @field_validator("user_query")
    @classmethod
    def validate_non_empty_query(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("user_query must not be empty or whitespace only.")
        return v.strip()


class CareerChatResponse(BaseModel):
    """
    Typed response representing non-authoritative natural language explanation.
    Never asserts new facts, never modifies VerifiedContext, and contains no
    authoritative SkillForge fields (e.g. demand_score, skill_classification).
    """
    explanation: str = Field(
        ...,
        description="Evidence-grounded explanatory text generated by Qwen or insufficient-evidence notice",
    )
    model: str = Field(
        "qwen3:8b",
        description="Model identifier responsible for generation",
    )
    status: ChatResponseStatus = Field(
        ChatResponseStatus.EXPLANATORY,
        description="EXPLANATORY for grounded responses, INSUFFICIENT_EVIDENCE when context lacks required facts",
    )
    referenced_skill_ids: Tuple[UUID, ...] = Field(
        default_factory=tuple,
        description="Canonical skill UUIDs from VerifiedContext referenced in the query/response",
    )
    retrieved_evidence: Tuple[RAGRetrievalResult, ...] = Field(
        default_factory=tuple,
        description="Retrieved supporting evidence chunks used for explanation",
    )
    usage: Optional[ChatUsageStats] = Field(
        default=None,
        description="Strongly-typed Ollama execution telemetry",
    )

    model_config = ConfigDict(frozen=True, extra="forbid")
