"""
Deterministic Security, IDOR, and Contract Tests for Checkpoint P5-D:
Verification API + Security Boundary.

Tests all 32 required API security, IDOR, PAT handling, and contract behaviors:
1. authenticated candidate can verify own roadmap milestone
2. unauthenticated request is rejected (401)
3. user A cannot verify user B's roadmap (403)
4. user A cannot GET user B's latest verification (403)
5. milestone from another roadmap cannot be paired with roadmap URL (404)
6. user A cannot verify user B's repository (403)
7. forked repository is rejected (422)
8. repository owner mismatch is rejected (403)
9. Authorization Bearer PAT is accepted (200)
10. missing Authorization token follows existing auth/error behavior (401)
11. PAT in JSON body is rejected/not accepted (422)
12. PAT in query parameter is rejected/not accepted (400)
13. PAT never appears in response (sentinel token check)
14. PAT never appears in persisted MilestoneVerification.details (sentinel token check)
15. PAT never appears in logs generated by the route/service (sentinel token check)
16. client cannot supply user_id to impersonate another user (422 / 403)
17. client cannot supply verification status (422)
18. client cannot supply confidence (422)
19. client cannot supply skill score (422)
20. client cannot supply commit SHA to override server-resolved SHA (422)
21. latest verification returns only the authenticated candidate's record
22. latest verification does not trigger GitHub calls
23. no verification history returns appropriate 404/not-found
24. VERIFIED response is typed
25. PARTIAL response is typed
26. UNVERIFIED response is typed
27. FAILED infrastructure response is mapped correctly (429, 504, 502)
28. candidate failure is not mapped to FAILED
29. batch verifies milestones deterministically
30. batch preserves independent verification history
31. batch does not alter unrelated roadmap milestones
32. cross-candidate verification attempts do not leak data
"""

from datetime import datetime, timezone
import json
import logging
from unittest.mock import MagicMock, patch
import uuid
import httpx
import pytest
from fastapi import HTTPException
from fastapi.testclient import TestClient
from sqlalchemy.orm import Session

from app.db.database import SessionLocal
from app.db.models import (
    ApprovedProject,
    CandidateRoadmap,
    DemonstratedSkill,
    GitHubRepository,
    JobRole,
    MilestoneVerification,
    ProjectEvidence,
    RoadmapMilestone,
    Skill,
    User,
)
from app.main import app

client = TestClient(app)

SENTINEL_PAT = "ghp_TEST_SECRET_DO_NOT_LEAK"

MOCK_TREE_VERIFIED = [
    {"path": "main.py", "type": "blob", "size": 120},
    {"path": "Dockerfile", "type": "blob", "size": 150},
]
MOCK_FILES_VERIFIED = {
    "main.py": "from pydantic import BaseModel, ConfigDict\n\nclass Item(BaseModel):\n    name: str\n    model_config = ConfigDict(frozen=True)\n",
    "Dockerfile": "FROM python:3.12-slim\nWORKDIR /app\nCMD ['uvicorn', 'main:app']\n",
}

MOCK_FILES_PARTIAL = {
    "main.py": "# Incomplete implementation without pydantic\nclass Item:\n    pass\n",
    "Dockerfile": "FROM python:3.12-slim\n# Missing WORKDIR\nCMD ['uvicorn', 'main:app']\n",
}


# -----------------------------------------------------------------------------
# Fixtures
# -----------------------------------------------------------------------------

@pytest.fixture
def db_session():
    """Provides a database session for test teardown and verification."""
    session = SessionLocal()
    try:
        yield session
    finally:
        session.rollback()
        session.close()


@pytest.fixture
def seed_data(db_session: Session):
    """Seed comprehensive test data for candidates, repos, roadmaps, and milestones."""
    # 1. Users
    user_ada_id = uuid.uuid4()
    candidate = User(
        id=user_ada_id,
        email=f"ada_{user_ada_id.hex[:6]}@example.com",
        full_name="Ada Lovelace",
    )
    db_session.add(candidate)

    user_charles_id = uuid.uuid4()
    other_user = User(
        id=user_charles_id,
        email=f"charles_{user_charles_id.hex[:6]}@example.com",
        full_name="Charles Babbage",
    )
    db_session.add(other_user)

    # 2. Skills & Role
    skill = db_session.query(Skill).filter(Skill.slug == "fastapi").first()
    if not skill:
        skill = Skill(id=uuid.uuid4(), name="FastAPI", slug=f"fastapi-{uuid.uuid4().hex[:4]}")
        db_session.add(skill)

    skill2 = db_session.query(Skill).filter(Skill.slug == "docker").first()
    if not skill2:
        skill2 = Skill(id=uuid.uuid4(), name="Docker", slug=f"docker-{uuid.uuid4().hex[:4]}")
        db_session.add(skill2)

    role = db_session.query(JobRole).first()
    if not role:
        role = JobRole(id=uuid.uuid4(), title="Backend Engineer", slug=f"backend-{uuid.uuid4().hex[:4]}")
        db_session.add(role)

    # 3. Approved Project
    project = ApprovedProject(
        id=uuid.uuid4(),
        skill_id=skill.id,
        role_id=role.id,
        title="Production FastAPI Microservice",
        description="Build a production-grade FastAPI microservice.",
        difficulty="INTERMEDIATE",
        deliverables=["main.py", "Dockerfile"],
        verification_criteria=["pydantic_v2_models", "explicit_workdir"],
        estimated_hours=8,
    )
    db_session.add(project)

    # 4. Repositories
    repo = GitHubRepository(
        id=uuid.uuid4(),
        user_id=candidate.id,
        repo_name="fastapi-app",
        full_name="candidate-ada/fastapi-app",
        repo_url="https://github.com/candidate-ada/fastapi-app",
        default_branch="main",
        is_fork=False,
        repo_metadata={"owner": "candidate-ada", "commit_sha": "a1b2c3d4e5f67890123456789abcdef012345678"},
    )
    db_session.add(repo)

    other_repo = GitHubRepository(
        id=uuid.uuid4(),
        user_id=other_user.id,
        repo_name="charles-app",
        full_name="charles/charles-app",
        repo_url="https://github.com/charles/charles-app",
        default_branch="main",
        is_fork=False,
        repo_metadata={"owner": "charles", "commit_sha": "b2c3d4e5f67890123456789abcdef0123456789a"},
    )
    db_session.add(other_repo)

    forked_repo = GitHubRepository(
        id=uuid.uuid4(),
        user_id=candidate.id,
        repo_name="forked-app",
        full_name="candidate-ada/forked-app",
        repo_url="https://github.com/candidate-ada/forked-app",
        default_branch="main",
        is_fork=True,
        repo_metadata={"owner": "candidate-ada"},
    )
    db_session.add(forked_repo)

    # 5. Roadmaps
    roadmap = CandidateRoadmap(
        id=uuid.uuid4(),
        user_id=candidate.id,
        role_id=role.id,
        target_role_title=role.title,
        status="ACTIVE",
        summary_metadata={"github_username": "candidate-ada"},
    )
    db_session.add(roadmap)

    other_roadmap = CandidateRoadmap(
        id=uuid.uuid4(),
        user_id=other_user.id,
        role_id=role.id,
        target_role_title=role.title,
        status="ACTIVE",
        summary_metadata={"github_username": "charles"},
    )
    db_session.add(other_roadmap)

    # 6. Milestones
    m1 = RoadmapMilestone(
        id=uuid.uuid4(),
        roadmap_id=roadmap.id,
        skill_id=skill.id,
        order_index=1,
        status="NOT_STARTED",
        gap_status="MISSING",
        reason="Primary backend milestone",
        project_id=project.id,
    )
    db_session.add(m1)

    m2 = RoadmapMilestone(
        id=uuid.uuid4(),
        roadmap_id=roadmap.id,
        skill_id=skill2.id,
        order_index=2,
        status="NOT_STARTED",
        gap_status="MISSING",
        reason="Secondary docker milestone",
    )
    db_session.add(m2)

    other_m1 = RoadmapMilestone(
        id=uuid.uuid4(),
        roadmap_id=other_roadmap.id,
        skill_id=skill.id,
        order_index=1,
        status="NOT_STARTED",
        gap_status="MISSING",
        reason="Charles milestone",
    )
    db_session.add(other_m1)

    # 7. Demonstrated Skill Evidence
    evidence = ProjectEvidence(
        id=uuid.uuid4(),
        user_id=candidate.id,
        repo_id=repo.id,
        skill_id=skill.id,
        evidence_type="dependency",
        file_path="requirements.txt",
        artifact_name="requirements.txt",
        evidence_description="FastAPI dependency declared",
        confidence_score=0.90,
    )
    db_session.add(evidence)

    db_session.commit()

    created_ids = {
        "candidate_id": candidate.id,
        "other_user_id": other_user.id,
        "repo_id": repo.id,
        "other_repo_id": other_repo.id,
        "forked_repo_id": forked_repo.id,
        "roadmap_id": roadmap.id,
        "other_roadmap_id": other_roadmap.id,
        "milestone_id": m1.id,
        "milestone_2_id": m2.id,
        "other_milestone_id": other_m1.id,
        "evidence_id": evidence.id,
        "project_id": project.id,
    }

    yield {
        "candidate": candidate,
        "other_user": other_user,
        "repo": repo,
        "other_repo": other_repo,
        "forked_repo": forked_repo,
        "roadmap": roadmap,
        "other_roadmap": other_roadmap,
        "milestone": m1,
        "milestone_2": m2,
        "other_milestone": other_m1,
        "project": project,
        "skill": skill,
        "skill2": skill2,
    }

    # Teardown: clean up created audit records and seed data
    db_session.query(MilestoneVerification).filter(
        MilestoneVerification.roadmap_id.in_([created_ids["roadmap_id"], created_ids["other_roadmap_id"]])
    ).delete(synchronize_session=False)
    db_session.query(ProjectEvidence).filter(ProjectEvidence.id == created_ids["evidence_id"]).delete(synchronize_session=False)
    db_session.query(RoadmapMilestone).filter(
        RoadmapMilestone.id.in_([created_ids["milestone_id"], created_ids["milestone_2_id"], created_ids["other_milestone_id"]])
    ).delete(synchronize_session=False)
    db_session.query(CandidateRoadmap).filter(
        CandidateRoadmap.id.in_([created_ids["roadmap_id"], created_ids["other_roadmap_id"]])
    ).delete(synchronize_session=False)
    db_session.query(ApprovedProject).filter(
        ApprovedProject.id == created_ids["project_id"]
    ).delete(synchronize_session=False)
    db_session.query(GitHubRepository).filter(
        GitHubRepository.id.in_([created_ids["repo_id"], created_ids["other_repo_id"], created_ids["forked_repo_id"]])
    ).delete(synchronize_session=False)
    db_session.query(User).filter(
        User.id.in_([created_ids["candidate_id"], created_ids["other_user_id"]])
    ).delete(synchronize_session=False)
    db_session.commit()


# -----------------------------------------------------------------------------
# 1-8: Core Verification & IDOR / Ownership Security
# -----------------------------------------------------------------------------

def test_01_authenticated_candidate_can_verify_own_milestone(seed_data):
    """1. Authenticated candidate can verify own roadmap milestone and receives typed VERIFIED response."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )

        assert res.status_code == 200
        data = res.json()
        assert data["status"] == "VERIFIED"
        assert data["confidence"] is not None
        assert data["confidence"] >= 0.85
        assert data["milestone_status"] == "VERIFIED"
        assert data["commit_sha"] == "a1b2c3d4e5f67890123456789abcdef012345678"
        assert data["milestone_id"] == str(d["milestone"].id)
        assert data["roadmap_id"] == str(d["roadmap"].id)
        assert data["user_id"] == str(d["candidate"].id)


def test_02_unauthenticated_request_is_rejected(seed_data):
    """2. Request without X-User-Id authentication is rejected with 401."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={"Authorization": f"Bearer {SENTINEL_PAT}"},
        json={"repository_id": str(d["repo"].id)},
    )
    assert res.status_code == 401


def test_03_user_a_cannot_verify_user_b_roadmap(seed_data):
    """3. Candidate Charles cannot verify Candidate Ada's roadmap milestone (403 Forbidden)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["other_user"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["repo"].id)},
    )
    assert res.status_code == 403
    assert "Cross-user access denied" in res.json()["detail"]


def test_04_user_a_cannot_get_user_b_latest_verification(seed_data, db_session):
    """4. Candidate Charles cannot GET Candidate Ada's latest verification (403 Forbidden)."""
    d = seed_data
    # Seed verification record for Ada
    v = MilestoneVerification(
        id=uuid.uuid4(),
        milestone_id=d["milestone"].id,
        roadmap_id=d["roadmap"].id,
        user_id=d["candidate"].id,
        repository_id=d["repo"].id,
        commit_sha="a1b2c3d4e5f67890123456789abcdef012345678",
        status="VERIFIED",
        confidence=0.92,
        details={"score": 0.92},
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(v)
    db_session.commit()

    res = client.get(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verification",
        headers={"X-User-Id": str(d["other_user"].id)},
    )
    assert res.status_code == 403


def test_05_milestone_from_another_roadmap_rejected(seed_data):
    """5. Milestone belonging to roadmap B cannot be paired with roadmap A URL (404 Not Found)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['other_milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["repo"].id)},
    )
    assert res.status_code == 404
    assert "does not belong to roadmap" in res.json()["detail"]


def test_06_user_a_cannot_verify_user_b_repository(seed_data):
    """6. Candidate Ada cannot supply Candidate Charles's repository (403 Forbidden)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["other_repo"].id)},
    )
    assert res.status_code == 403
    assert "Cross-user access denied" in res.json()["detail"]


def test_07_forked_repository_is_rejected(seed_data):
    """7. Forked repository is rejected (422 Unprocessable Entity)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["forked_repo"].id)},
    )
    assert res.status_code == 422
    assert "is a fork" in res.json()["detail"]


def test_08_repository_owner_mismatch_is_rejected(seed_data):
    """8. Repository owner mismatch against connected GitHub account is rejected (403 Forbidden)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
            "X-GitHub-Username": "malicious-impersonator",
        },
        json={"repository_id": str(d["repo"].id)},
    )
    assert res.status_code == 403
    assert "owner does not match" in res.json()["detail"]


# -----------------------------------------------------------------------------
# 9-15: PAT Handling & Secret Leak Prevention
# -----------------------------------------------------------------------------

def test_09_authorization_bearer_pat_accepted(seed_data):
    """9. Authorization Bearer PAT is accepted at API boundary."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200


def test_10_missing_authorization_token_rejected(seed_data):
    """10. Missing Authorization header is rejected with 401."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={"X-User-Id": str(d["candidate"].id)},
        json={"repository_id": str(d["repo"].id)},
    )
    assert res.status_code == 401
    assert "Missing Authorization header" in res.json()["detail"]


def test_11_pat_in_json_body_is_rejected(seed_data):
    """11. PAT / access_token in JSON request body is strictly rejected (422 Unprocessable Entity)."""
    d = seed_data
    # Extra field access_token forbidden
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "access_token": SENTINEL_PAT,
        },
    )
    assert res.status_code == 422

    # Extra field token forbidden
    res2 = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "token": SENTINEL_PAT,
        },
    )
    assert res2.status_code == 422


def test_12_pat_in_query_parameter_is_rejected(seed_data):
    """12. PAT in query parameter is rejected (400 Bad Request)."""
    d = seed_data
    for q_key in ("token", "pat", "access_token", "github_token"):
        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify?{q_key}={SENTINEL_PAT}",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 400
        assert "prohibited in query parameters" in res.json()["detail"]


def test_13_pat_never_appears_in_response(seed_data):
    """13. Sentinel PAT never appears in the API response JSON."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )

        assert res.status_code == 200
        assert SENTINEL_PAT not in res.text


def test_14_pat_never_appears_in_persisted_milestone_verification_details(seed_data, db_session):
    """14. Sentinel PAT never appears in persisted MilestoneVerification.details."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200

        rec = (
            db_session.query(MilestoneVerification)
            .filter(MilestoneVerification.milestone_id == d["milestone"].id)
            .order_by(MilestoneVerification.created_at.desc())
            .first()
        )
        assert rec is not None
        details_str = json.dumps(rec.details)
        assert SENTINEL_PAT not in details_str


def test_15_pat_never_appears_in_logs(seed_data, caplog):
    """15. Sentinel PAT never appears in logs generated by route or service."""
    d = seed_data
    caplog.set_level(logging.DEBUG)

    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200
        assert SENTINEL_PAT not in caplog.text


# -----------------------------------------------------------------------------
# 16-20: Server Authority / Client Parameter Tampering Prevention
# -----------------------------------------------------------------------------

def test_16_client_cannot_supply_user_id_to_impersonate(seed_data):
    """16. Client cannot supply user_id in JSON body (422) or conflicting query param (403)."""
    d = seed_data
    # Body injection -> 422
    res_body = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "user_id": str(d["other_user"].id),
        },
    )
    assert res_body.status_code == 422

    # Query param conflict -> 403
    res_query = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify?user_id={d['other_user'].id}",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["repo"].id)},
    )
    assert res_query.status_code == 403


def test_17_client_cannot_supply_verification_status(seed_data):
    """17. Client cannot supply verification status in body (422 Unprocessable Entity)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "status": "VERIFIED",
        },
    )
    assert res.status_code == 422


def test_18_client_cannot_supply_confidence(seed_data):
    """18. Client cannot supply confidence score in body (422 Unprocessable Entity)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "confidence": 0.99,
        },
    )
    assert res.status_code == 422


def test_19_client_cannot_supply_skill_score(seed_data):
    """19. Client cannot supply skill score in body (422 Unprocessable Entity)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "skill_score": 0.95,
        },
    )
    assert res.status_code == 422


def test_20_client_cannot_supply_commit_sha(seed_data):
    """20. Client cannot supply commit SHA in body to override server resolution (422 Unprocessable Entity)."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={
            "repository_id": str(d["repo"].id),
            "commit_sha": "fake_override_sha_1234567890abcdef",
        },
    )
    assert res.status_code == 422


# -----------------------------------------------------------------------------
# 21-23: Latest Verification Query Endpoint
# -----------------------------------------------------------------------------

def test_21_latest_verification_returns_candidates_record(seed_data, db_session):
    """21. Latest verification returns only the authenticated candidate's record."""
    d = seed_data
    v = MilestoneVerification(
        id=uuid.uuid4(),
        milestone_id=d["milestone"].id,
        roadmap_id=d["roadmap"].id,
        user_id=d["candidate"].id,
        repository_id=d["repo"].id,
        commit_sha="a1b2c3d4e5f67890123456789abcdef012345678",
        status="VERIFIED",
        confidence=0.91,
        details={"audit": "clean"},
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(v)
    db_session.commit()

    res = client.get(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verification",
        headers={"X-User-Id": str(d["candidate"].id)},
    )
    assert res.status_code == 200
    data = res.json()
    assert data["id"] == str(v.id)
    assert data["status"] == "VERIFIED"
    assert data["commit_sha"] == "a1b2c3d4e5f67890123456789abcdef012345678"


def test_22_latest_verification_does_not_trigger_github_calls(seed_data, db_session):
    """22. Latest verification does not trigger external GitHub calls or mutations."""
    d = seed_data
    v = MilestoneVerification(
        id=uuid.uuid4(),
        milestone_id=d["milestone"].id,
        roadmap_id=d["roadmap"].id,
        user_id=d["candidate"].id,
        repository_id=d["repo"].id,
        commit_sha="a1b2c3d4e5f67890123456789abcdef012345678",
        status="VERIFIED",
        confidence=0.91,
        details={"audit": "clean"},
        created_at=datetime.now(timezone.utc),
    )
    db_session.add(v)
    db_session.commit()

    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree") as mock_tree, \
         patch("app.services.verification_service.github_analyzer.analyze_repository") as mock_analyze:

        res = client.get(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verification",
            headers={"X-User-Id": str(d["candidate"].id)},
        )
        assert res.status_code == 200
        mock_tree.assert_not_called()
        mock_analyze.assert_not_called()


def test_23_no_verification_history_returns_404(seed_data):
    """23. Querying latest verification with no history returns 404 Not Found."""
    d = seed_data
    res = client.get(
        f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verification",
        headers={"X-User-Id": str(d["candidate"].id)},
    )
    assert res.status_code == 404
    assert "No verification record found" in res.json()["detail"]


# -----------------------------------------------------------------------------
# 24-28: Verification Status Types & Infrastructure Error Mappings
# -----------------------------------------------------------------------------

def test_24_verified_response_is_typed(seed_data):
    """24. Full pass yields typed response with status VERIFIED."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200
        assert res.json()["status"] == "VERIFIED"


def test_25_partial_response_is_typed(seed_data):
    """25. Partial criteria satisfaction yields typed response with status PARTIAL."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_PARTIAL.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200
        assert res.json()["status"] == "PARTIAL"


def test_26_unverified_response_is_typed(seed_data):
    """26. Zero deliverable / empty repo yields typed response with status UNVERIFIED."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=[]), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", return_value=None), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone_2'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200
        assert res.json()["status"] == "UNVERIFIED"


def test_27_failed_infrastructure_response_is_mapped_correctly(seed_data, db_session):
    """27. Infrastructure failures map to 429, 504, 502 while preserving FAILED DB record."""
    d = seed_data

    # Rate limit -> 429
    with patch("app.services.verification_service.github_analyzer.analyze_repository", side_effect=HTTPException(429, "Rate limit")):
        res_429 = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res_429.status_code == 429

    # Timeout -> 504
    with patch("app.services.verification_service.github_analyzer.analyze_repository", side_effect=httpx.TimeoutException("Timeout")):
        res_504 = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res_504.status_code == 504

    # Upstream 502 -> 502
    with patch("app.services.verification_service.github_analyzer.analyze_repository", side_effect=httpx.RequestError("Upstream bad gateway")):
        res_502 = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res_502.status_code == 502

    # Verify FAILED record was persisted in DB
    failed_rec = (
        db_session.query(MilestoneVerification)
        .filter(MilestoneVerification.milestone_id == d["milestone"].id, MilestoneVerification.status == "FAILED")
        .first()
    )
    assert failed_rec is not None


def test_28_candidate_failure_is_not_mapped_to_failed(seed_data):
    """28. Candidate evaluation failures (missing deliverables) result in 200 UNVERIFIED, not 5xx FAILED."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=[]), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", return_value=None), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/milestones/{d['milestone_2'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200
        assert res.json()["status"] in ("PARTIAL", "UNVERIFIED")
        assert res.json()["status"] != "FAILED"


# -----------------------------------------------------------------------------
# 29-32: Batch Verification & Data Isolation
# -----------------------------------------------------------------------------

def test_29_batch_verifies_milestones_deterministically(seed_data):
    """29. Batch endpoint verifies all roadmap milestones sequentially in deterministic order."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )

        assert res.status_code == 200
        data = res.json()
        assert data["roadmap_id"] == str(d["roadmap"].id)
        assert data["total_milestones"] == 2
        assert len(data["results"]) == 2
        assert data["results"][0]["milestone_id"] == str(d["milestone"].id)
        assert data["results"][1]["milestone_id"] == str(d["milestone_2"].id)


def test_30_batch_preserves_independent_verification_history(seed_data, db_session):
    """30. Batch verification creates independent MilestoneVerification records for each milestone."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200

        records = (
            db_session.query(MilestoneVerification)
            .filter(MilestoneVerification.roadmap_id == d["roadmap"].id)
            .all()
        )
        assert len(records) >= 2
        verified_m_ids = {r.milestone_id for r in records}
        assert d["milestone"].id in verified_m_ids
        assert d["milestone_2"].id in verified_m_ids


def test_31_batch_does_not_alter_unrelated_roadmap_milestones(seed_data, db_session):
    """31. Batch verification never alters milestones on another candidate's roadmap."""
    d = seed_data
    with patch("app.services.verification_service.github_analyzer.fetch_repo_tree", return_value=MOCK_TREE_VERIFIED), \
         patch("app.services.verification_service.github_analyzer.fetch_file_content", side_effect=lambda fn, p, token=None: MOCK_FILES_VERIFIED.get(p)), \
         patch("app.services.verification_service.github_analyzer.analyze_repository", return_value=([], set())):

        res = client.post(
            f"/api/v1/roadmap/{d['roadmap'].id}/verify",
            headers={
                "X-User-Id": str(d["candidate"].id),
                "Authorization": f"Bearer {SENTINEL_PAT}",
            },
            json={"repository_id": str(d["repo"].id)},
        )
        assert res.status_code == 200

        refreshed_other_m = (
            db_session.query(RoadmapMilestone)
            .filter(RoadmapMilestone.id == d["other_milestone"].id)
            .first()
        )
        assert refreshed_other_m.status == "NOT_STARTED"


def test_32_cross_candidate_verification_does_not_leak_data(seed_data):
    """32. Cross-candidate verification attempts do not leak repository names, tokens, or emails in errors."""
    d = seed_data
    res = client.post(
        f"/api/v1/roadmap/{d['other_roadmap'].id}/milestones/{d['other_milestone'].id}/verify",
        headers={
            "X-User-Id": str(d["candidate"].id),
            "Authorization": f"Bearer {SENTINEL_PAT}",
        },
        json={"repository_id": str(d["other_repo"].id)},
    )
    assert res.status_code == 403
    detail = res.json()["detail"]
    assert d["other_user"].email not in detail
    assert SENTINEL_PAT not in detail
