/**
 * Frontend Authentication & Session Contract Test Suite
 *
 * Validates Login Phase 5 requirements:
 * 1. Login success
 * 2. Signup success
 * 3. Invalid credentials (safe error, no leak)
 * 4. Session restoration via /auth/me
 * 5. Logout revokes server session & clears state
 * 6. Unauthenticated state (401 returns null without throwing)
 * 7. Google login redirect initiation URL
 * 8. Backend 401 transitions to logged-out state
 * 9. No session token in localStorage
 * 10. No X-User-Id generated by authenticated frontend requests (uses credentials: include)
 * 11. Active resume state comes from backend (PUT /api/v1/resumes/{id}/activate)
 * 12. GitHub connection state comes from backend (POST /api/v1/github/disconnect)
 */

import { test, describe, beforeEach } from "node:test";
import assert from "node:assert/strict";

// In-memory mock localStorage
class MockLocalStorage {
  constructor() {
    this.store = new Map();
  }
  getItem(key) {
    return this.store.get(key) || null;
  }
  setItem(key, value) {
    this.store.set(key, String(value));
  }
  removeItem(key) {
    this.store.delete(key);
  }
  clear() {
    this.store.clear();
  }
  get length() {
    return this.store.size;
  }
  key(index) {
    return Array.from(this.store.keys())[index] || null;
  }
}

// Global browser mocks for Node environment
globalThis.window = globalThis;
globalThis.localStorage = new MockLocalStorage();
globalThis.CustomEvent = class CustomEvent {
  constructor(type, eventInitDict) {
    this.type = type;
    this.detail = eventInitDict?.detail;
  }
};
globalThis.Event = class Event {
  constructor(type) {
    this.type = type;
  }
};
globalThis.dispatchEvent = () => true;
globalThis.addEventListener = () => {};
globalThis.removeEventListener = () => {};

// Import modules under test
const authModule = await import("../lib/auth.ts");
const apiModule = await import("../lib/api.ts");

describe("Login Phase 5 — Frontend Auth & Session Contract", () => {
  let capturedFetchCalls = [];

  beforeEach(() => {
    capturedFetchCalls = [];
    localStorage.clear();

    // Mock global fetch
    globalThis.fetch = async (url, options = {}) => {
      capturedFetchCalls.push({ url, options });
      const urlStr = String(url);

      // 1. POST /api/v1/auth/login
      if (urlStr.includes("/api/v1/auth/login")) {
        const body = JSON.parse(options.body || "{}");
        if (body.email === "test@example.com" && body.password === "correct_password") {
          return {
            ok: true,
            status: 200,
            json: async () => ({
              id: "99999999-9999-4999-9999-999999999999",
              email: "test@example.com",
              full_name: "Test Candidate",
              target_role: "Full Stack Engineer",
              auth_provider: "local",
              is_active: true,
              active_resume_id: "11111111-1111-4111-8111-111111111111",
              connected_github_username: "testoctocat",
              created_at: new Date().toISOString(),
            }),
          };
        }
        return {
          ok: false,
          status: 401,
          json: async () => ({ detail: "Invalid email or password." }),
        };
      }

      // 2. POST /api/v1/auth/signup
      if (urlStr.includes("/api/v1/auth/signup")) {
        const body = JSON.parse(options.body || "{}");
        if (body.email === "existing@example.com") {
          return {
            ok: false,
            status: 409,
            json: async () => ({ detail: "An account with this email already exists." }),
          };
        }
        return {
          ok: true,
          status: 201,
          json: async () => ({
            id: "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa",
            email: body.email,
            full_name: body.full_name,
            target_role: body.target_role,
            auth_provider: "local",
            is_active: true,
            active_resume_id: null,
            connected_github_username: null,
            created_at: new Date().toISOString(),
          }),
        };
      }

      // 3. GET /api/v1/auth/me
      if (urlStr.includes("/api/v1/auth/me")) {
        if (options.headers?.["X-Force-401"] || globalThis.__force401) {
          return {
            ok: false,
            status: 401,
            json: async () => ({ detail: "Authentication required. Please log in." }),
          };
        }
        return {
          ok: true,
          status: 200,
          json: async () => ({
            id: "99999999-9999-4999-9999-999999999999",
            email: "test@example.com",
            full_name: "Test Candidate",
            target_role: "Full Stack Engineer",
            auth_provider: "local",
            is_active: true,
            active_resume_id: "11111111-1111-4111-8111-111111111111",
            connected_github_username: "testoctocat",
            created_at: new Date().toISOString(),
          }),
        };
      }

      // 4. POST /api/v1/auth/logout
      if (urlStr.includes("/api/v1/auth/logout")) {
        return {
          ok: true,
          status: 200,
          json: async () => ({ message: "Logged out successfully" }),
        };
      }

      // 5. PUT /api/v1/resumes/{id}/activate
      if (urlStr.includes("/resumes/") && urlStr.includes("/activate")) {
        return {
          ok: true,
          status: 200,
          json: async () => ({
            message: "Active resume updated successfully",
            active_resume_id: "22222222-2222-4222-8222-222222222222",
            filename: "updated_resume.pdf",
          }),
        };
      }

      // 6. POST /api/v1/github/disconnect
      if (urlStr.includes("/github/disconnect")) {
        return {
          ok: true,
          status: 200,
          json: async () => ({
            message: "GitHub account disconnected successfully",
            connected: false,
          }),
        };
      }

      // 7. GET /api/v1/resumes/{id}
      if (urlStr.includes("/api/v1/resumes/")) {
        return {
          ok: true,
          status: 200,
          json: async () => ({
            resume_id: "11111111-1111-4111-8111-111111111111",
            user_id: "99999999-9999-4999-9999-999999999999",
            filename: "candidate_cv.pdf",
            file_type: "pdf",
            file_size: 1024,
            status: "parsed",
            created_at: new Date().toISOString(),
            detected_sections: ["experience", "education", "skills"],
            claimed_skills: [],
          }),
        };
      }

      return {
        ok: true,
        status: 200,
        json: async () => ({ status: "ok" }),
      };
    };
  });

  test("1. Login success wires credentials: include and returns user profile", async () => {
    const res = await authModule.loginCandidate({
      email: "test@example.com",
      password: "correct_password",
      rememberMe: true,
    });

    assert.equal(res.success, true);
    assert.ok(res.user);
    assert.equal(res.user.email, "test@example.com");
    assert.equal(res.user.active_resume_id, "11111111-1111-4111-8111-111111111111");

    const call = capturedFetchCalls.find((c) => c.url.includes("/api/v1/auth/login"));
    assert.ok(call);
    assert.equal(call.options.credentials, "include");
    assert.equal(localStorage.getItem(authModule.REMEMBER_ME_STORAGE_KEY), "true");
    assert.equal(localStorage.getItem(authModule.REMEMBER_EMAIL_STORAGE_KEY), "test@example.com");
  });

  test("2. Signup success creates account with 8+ char password and credentials: include", async () => {
    const res = await authModule.signupCandidate({
      email: "newuser@example.com",
      password: "valid_password_123",
      fullName: "New Candidate",
      targetRole: "Backend Engineer",
    });

    assert.equal(res.success, true);
    assert.ok(res.user);
    assert.equal(res.user.email, "newuser@example.com");
    assert.equal(res.user.full_name, "New Candidate");

    const call = capturedFetchCalls.find((c) => c.url.includes("/api/v1/auth/signup"));
    assert.ok(call);
    assert.equal(call.options.credentials, "include");
  });

  test("3. Invalid credentials returns safe error without exposing account existence", async () => {
    const res = await authModule.loginCandidate({
      email: "test@example.com",
      password: "wrong_password",
    });

    assert.equal(res.success, false);
    assert.equal(res.statusCode, 401);
    assert.ok(res.error?.includes("Invalid email or password"));
    // Ensure no password in error
    assert.ok(!res.error?.includes("wrong_password"));
  });

  test("4. Session restoration via GET /auth/me returns authenticated user", async () => {
    globalThis.__force401 = false;
    const user = await authModule.fetchCurrentCandidate();

    assert.ok(user);
    assert.equal(user.email, "test@example.com");
    assert.equal(user.connected_github_username, "testoctocat");

    const call = capturedFetchCalls.find((c) => c.url.includes("/api/v1/auth/me"));
    assert.ok(call);
    assert.equal(call.options.credentials, "include");
  });

  test("5. Logout calls POST /auth/logout and purges client profile and legacy keys", async () => {
    // Pre-populate some legacy keys
    localStorage.setItem("skillforge_candidate_user_id", "old-uuid");
    localStorage.setItem("skillforge_active_resume_id", "old-resume");
    localStorage.setItem("skillforge_user_profile", JSON.stringify({ id: "test" }));

    await authModule.logoutCandidate();

    const call = capturedFetchCalls.find((c) => c.url.includes("/api/v1/auth/logout"));
    assert.ok(call);
    assert.equal(call.options.credentials, "include");

    assert.equal(localStorage.getItem("skillforge_user_profile"), null);
    assert.equal(localStorage.getItem("skillforge_candidate_user_id"), null);
    assert.equal(localStorage.getItem("skillforge_active_resume_id"), null);
  });

  test("6. Unauthenticated state returns null cleanly without throwing", async () => {
    globalThis.__force401 = true;
    const user = await authModule.fetchCurrentCandidate();
    assert.equal(user, null);
    globalThis.__force401 = false;
  });

  test("7. Google login redirect initiation points to /api/v1/auth/google/login", () => {
    const apiBase = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
    const googleLoginUrl = `${apiBase}/api/v1/auth/google/login`;
    assert.equal(googleLoginUrl.endsWith("/api/v1/auth/google/login"), true);
  });

  test("8. Backend 401 clears cached user profile and legacy storage", async () => {
    localStorage.setItem("skillforge_user_profile", JSON.stringify({ id: "stale" }));
    localStorage.setItem("skillforge_candidate_user_id", "stale-candidate");

    globalThis.__force401 = true;
    const user = await authModule.fetchCurrentCandidate();
    globalThis.__force401 = false;

    assert.equal(user, null);
    assert.equal(localStorage.getItem("skillforge_user_profile"), null);
    assert.equal(localStorage.getItem("skillforge_candidate_user_id"), null);
  });

  test("9. No session token in localStorage", async () => {
    await authModule.loginCandidate({
      email: "test@example.com",
      password: "correct_password",
      rememberMe: true,
    });

    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      const value = localStorage.getItem(key);
      assert.ok(!key.includes("token"), `Found token key in localStorage: ${key}`);
      assert.ok(!key.includes("session"), `Found session key in localStorage: ${key}`);
      assert.ok(!value?.includes("skillforge_session"), `Found session cookie value in localStorage for key ${key}`);
    }
  });

  test("10. No X-User-Id generated by authenticated frontend requests", async () => {
    await apiModule.fetchResumes();
    await apiModule.fetchResumeDetail("11111111-1111-4111-8111-111111111111");
    await apiModule.activateResume("22222222-2222-4222-8222-222222222222");
    await apiModule.disconnectGitHubAccount();

    for (const call of capturedFetchCalls) {
      const headers = call.options.headers || {};
      assert.equal(headers["X-User-Id"], undefined, `Request to ${call.url} included X-User-Id header`);
      if (!call.url.includes("/health")) {
        assert.equal(call.options.credentials, "include", `Request to ${call.url} did not include credentials: include`);
      }
    }
  });

  test("11. Active resume state comes from backend activateResume endpoint", async () => {
    const res = await apiModule.activateResume("22222222-2222-4222-8222-222222222222");
    assert.equal(res.success, true);
    assert.ok(res.data);
    assert.equal(res.data.active_resume_id, "22222222-2222-4222-8222-222222222222");
    assert.equal(res.data.filename, "updated_resume.pdf");

    const call = capturedFetchCalls.find((c) => c.url.includes("/resumes/22222222-2222-4222-8222-222222222222/activate"));
    assert.ok(call);
    assert.equal(call.options.method, "PUT");
    assert.equal(call.options.credentials, "include");
  });

  test("12. GitHub connection state comes from backend disconnect endpoint", async () => {
    const res = await apiModule.disconnectGitHubAccount();
    assert.equal(res.success, true);

    const call = capturedFetchCalls.find((c) => c.url.includes("/api/v1/github/disconnect"));
    assert.ok(call);
    assert.equal(call.options.method, "POST");
    assert.equal(call.options.credentials, "include");
  });
});
