from app.db.database import Base, engine, get_db, SessionLocal
from app.db.models import (
    User,
    Skill,
    Resume,
    SkillAlias,
    UserClaimedSkill,
    GitHubRepository,
    ProjectEvidence,
    DemonstratedSkill,
    JobRole,
    IndustrySkillDemand,
    SkillDemand,
    MarketJob,
    MarketJobSkill,
    MarketSkillDemand,
    MarketSkillDemandSnapshot,
    MarketSkillDemandGrowth,
    Conversation,
    Message,
    UserProfile,
    Roadmap,
    RoadmapStage,
    RoadmapSkill,
    RoadmapPrerequisite,
    LearningResource,
    UserRoadmapProgress,
    UserPracticeProgress,
)
from app.db.seed_roadmaps import seed_roadmaps, validate_seeded_roadmaps

__all__ = [
    "Base",
    "engine",
    "get_db",
    "SessionLocal",
    "User",
    "Skill",
    "Resume",
    "SkillAlias",
    "UserClaimedSkill",
    "GitHubRepository",
    "ProjectEvidence",
    "DemonstratedSkill",
    "JobRole",
    "IndustrySkillDemand",
    "SkillDemand",
    "MarketJob",
    "MarketJobSkill",
    "MarketSkillDemand",
    "MarketSkillDemandSnapshot",
    "MarketSkillDemandGrowth",
    "Conversation",
    "Message",
    "UserProfile",
    "Roadmap",
    "RoadmapStage",
    "RoadmapSkill",
    "RoadmapPrerequisite",
    "LearningResource",
    "UserRoadmapProgress",
    "UserPracticeProgress",
    "seed_roadmaps",
    "validate_seeded_roadmaps",
]

