from app.schemas.health import HealthResponse, DbHealthResponse
from app.schemas.user import UserBase, UserCreate, UserRead
from app.schemas.skill import (
    SkillBase,
    SkillCreate,
    SkillRead,
    ClaimedSkillItem,
    PaginationMeta,
    ClaimedSkillsResponse,
)
from app.schemas.resume import (
    ResumeUploadResponse,
    ResumeListItem,
    ResumeListResponse,
    ResumeDetailResponse,
)
from app.schemas.github import (
    GitHubConnectRequest,
    GitHubConnectData,
    GitHubConnectResponse,
    GitHubRepositoryItem,
    GitHubRepositoryListResponse,
    GitHubRepositoryDetailData,
    GitHubRepositoryDetailResponse,
)
from app.schemas.evidence import (
    GitHubAnalyzeRequest,
    DemonstratedSkillItem,
    GitHubAnalyzeData,
    GitHubAnalyzeResponse,
    ProjectEvidenceItem,
    ProjectEvidenceListResponse,
    ProjectEvidenceDetailResponse,
)

from app.schemas.demonstrated_skill import (
    SupportingRepositoryItem,
    DemonstratedSkillSummaryItem,
    DemonstratedSkillListResponse,
    DemonstratedSkillDetailData,
    DemonstratedSkillDetailResponse,
)
from app.schemas.demand import (
    JobRoleItem,
    JobRoleListResponse,
    JobRoleDetailResponse,
    SkillDemandItem,
    DemandPaginationMeta,
    SkillDemandListResponse,
    RoleSkillDemandItem,
    RoleDemandDetailData,
    RoleDemandDetailMeta,
    RoleDemandDetailResponse,
    DemandQualityAuditReport,
    DemandQualityAuditResponse,
)
from app.schemas.skill_gap import (
    SkillGapItem,
    SkillGapSummary,
    SkillGapResponseData,
    SkillGapMeta,
    SkillGapResponse,
    SkillGapAnalyzeRequest,
    PrioritizedGapItem,
    PrioritizedGapsSummary,
    PrioritizedGapsResponseData,
    PrioritizedGapsResponse,
)
from app.schemas.skill_gap_evidence import (
    ResumeEvidenceItem,
    GitHubEvidenceItem,
    DemonstratedSkillSummary,
    CandidateEvidenceData,
    MarketEvidenceData,
    DeterministicReasoningData,
    SkillGapEvidenceResponseData,
    SkillGapEvidenceResponse,
)

__all__ = [
    "HealthResponse",
    "DbHealthResponse",
    "UserBase",
    "UserCreate",
    "UserRead",
    "SkillBase",
    "SkillCreate",
    "SkillRead",
    "ClaimedSkillItem",
    "PaginationMeta",
    "ClaimedSkillsResponse",
    "ResumeUploadResponse",
    "ResumeListItem",
    "ResumeListResponse",
    "ResumeDetailResponse",
    "GitHubConnectRequest",
    "GitHubConnectData",
    "GitHubConnectResponse",
    "GitHubRepositoryItem",
    "GitHubRepositoryListResponse",
    "GitHubRepositoryDetailData",
    "GitHubRepositoryDetailResponse",
    "GitHubAnalyzeRequest",
    "DemonstratedSkillItem",
    "GitHubAnalyzeData",
    "GitHubAnalyzeResponse",
    "ProjectEvidenceItem",
    "ProjectEvidenceListResponse",
    "ProjectEvidenceDetailResponse",
    "SupportingRepositoryItem",
    "DemonstratedSkillSummaryItem",
    "DemonstratedSkillListResponse",
    "DemonstratedSkillDetailData",
    "DemonstratedSkillDetailResponse",
    "JobRoleItem",
    "JobRoleListResponse",
    "JobRoleDetailResponse",
    "SkillDemandItem",
    "DemandPaginationMeta",
    "SkillDemandListResponse",
    "RoleSkillDemandItem",
    "RoleDemandDetailData",
    "RoleDemandDetailMeta",
    "RoleDemandDetailResponse",
    "DemandQualityAuditReport",
    "DemandQualityAuditResponse",
    "SkillGapItem",
    "SkillGapSummary",
    "SkillGapResponseData",
    "SkillGapMeta",
    "SkillGapResponse",
    "SkillGapAnalyzeRequest",
    "PrioritizedGapItem",
    "PrioritizedGapsSummary",
    "PrioritizedGapsResponseData",
    "PrioritizedGapsResponse",
    "ResumeEvidenceItem",
    "GitHubEvidenceItem",
    "DemonstratedSkillSummary",
    "CandidateEvidenceData",
    "MarketEvidenceData",
    "DeterministicReasoningData",
    "SkillGapEvidenceResponseData",
    "SkillGapEvidenceResponse",
]

