"""
Pydantic Schemas for AI Roadmap PDF Narrative Generation and Validation.
Post-MVP Career Roadmap PDF Feature (Phase 3).

Core Invariants:
- Strict immutability and schema restrictions: ConfigDict(frozen=True, extra="forbid").
- Deeply typed collections (Tuple instead of mutable List).
- Separation of concerns:
  1. RoadmapPDFPersonalizedNarrative: Output generated by Gemini 2.5 Flash via LangChain.
  2. ValidatedRoadmapPDFContent: Final authoritative assembled document combining Phase 2
     deterministic facts (immutable, copied directly) with validated Gemini narrative text.
- Curated projects are recommended practical challenges, NOT candidate proof (is_candidate_proof=False).
- weekly_hours_recommendation remains None (never fabricated).
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.ai.context.roadmap_pdf_context import (
    PriorityTierLevel,
    SkillGapClassification,
    VerifiedApprovedProject,
    VerifiedApprovedResource,
    VerifiedCandidateEvidenceItem,
    VerifiedCandidateProfile,
    VerifiedMarketDemandFact,
    VerifiedReadinessMetrics,
    VerifiedRoadmapPrerequisite,
)


# ---------------------------------------------------------------------------
# 1. Gemini Structured Output Models (Target of with_structured_output)
# ---------------------------------------------------------------------------

class RoadmapPhaseNarrative(BaseModel):
    """Personalized explanatory text for a single sequenced roadmap phase."""
    skill_id: str = Field(
        ...,
        description="Canonical UUID string of the roadmap milestone skill being explained. Must match authoritative milestone skill_id exactly."
    )
    phase_title: str = Field(
        ...,
        description="Concise, action-oriented title for this roadmap phase (e.g., 'Mastering Containerized Service Architecture')."
    )
    personalized_rationale: str = Field(
        ...,
        description="Personalized explanation of why the candidate must learn this skill at this sequence position based on verified gaps."
    )
    key_topics: List[str] = Field(
        default_factory=list,
        description="2 to 5 specific, high-yield technical competencies to master in this phase."
    )
    expected_focus: Optional[str] = Field(
        None,
        description="Optional brief one-sentence focus summary for candidate study."
    )

    @field_validator("skill_id", mode="before")
    @classmethod
    def _coerce_skill_id(cls, v: Any) -> str:
        return str(v)

    model_config = ConfigDict(frozen=True, extra="forbid")


class SkillGapNarrative(BaseModel):
    """Personalized narrative explaining why an authoritative high-priority skill gap matters."""
    skill_id: str = Field(
        ...,
        description="Canonical UUID string of the prioritized skill gap. Must match an authoritative gap skill_id exactly."
    )
    why_it_matters: str = Field(
        ...,
        description="Concise engineering explanation of why this gap is critical for the target role."
    )
    suggested_focus: str = Field(
        ...,
        description="Targeted recommendation on what aspect of the skill to prioritize."
    )

    @field_validator("skill_id", mode="before")
    @classmethod
    def _coerce_skill_id(cls, v: Any) -> str:
        return str(v)

    model_config = ConfigDict(frozen=True, extra="forbid")


class RoadmapPDFPersonalizedNarrative(BaseModel):
    """
    Structured narrative generated exclusively by Gemini 2.5 Flash.
    Strictly forbids score fabrication, URL introduction, or skill reclassification.
    """
    personalized_subtitle: str = Field(
        ...,
        description="Candidate-tailored subtitle (e.g., 'Targeted Competency Pathway for Backend Engineer Roles')."
    )
    executive_summary: str = Field(
        ...,
        description="High-level narrative summarizing candidate's current verified baseline, key gaps, and strategic trajectory."
    )
    readiness_explanation: str = Field(
        ...,
        description="Professional contextual explanation of the candidate's deterministic readiness score without modifying the score."
    )
    top_gap_narratives: List[SkillGapNarrative] = Field(
        default_factory=list,
        description="Narrative explanations for top actionable skill gaps."
    )
    phases: List[RoadmapPhaseNarrative] = Field(
        ...,
        description="Ordered phase narratives matching the exact milestones in the canonical roadmap sequence."
    )
    immediate_next_steps: List[str] = Field(
        ...,
        description="2 to 5 concrete action items for the candidate to execute within the next 7-14 days."
    )
    closing_encouragement: str = Field(
        ...,
        description="Professional, empowering closing statement tailored to the candidate's career trajectory."
    )

    model_config = ConfigDict(frozen=True, extra="forbid")



# ---------------------------------------------------------------------------
# 2. Final Assembled & Validated Result Models (Consumed by Future ReportLab)
# ---------------------------------------------------------------------------

class ValidatedRoadmapPhase(BaseModel):
    """
    Complete verified milestone combining authoritative Phase 2 data with validated narrative.
    Authoritative fields are copied directly from Phase 2 and cannot be altered by Gemini.
    """
    # Authoritative Phase 2 facts (immutable)
    milestone_id: Optional[UUID] = Field(None, description="Database UUID if persisted")
    order_index: int = Field(..., ge=1, description="1-indexed sequence order in the roadmap")
    skill_id: UUID = Field(..., description="Canonical skill UUID")
    skill_name: str = Field(..., description="Canonical skill name")
    canonical_slug: str = Field(..., description="Taxonomy lookup slug")
    category: Optional[str] = Field(None, description="Taxonomy category")
    gap_status: SkillGapClassification = Field(..., description="Authoritative gap classification: MISSING or PARTIAL")
    priority_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Deterministic priority score")
    priority_level: Optional[PriorityTierLevel] = Field(None, description="Deterministic priority category")
    is_transitive_prerequisite: bool = Field(False, description="Whether dynamically scheduled as a prerequisite")
    deterministic_reason: str = Field(..., description="Authoritative deterministic reason for sequencing")
    status: str = Field("NOT_STARTED", description="Milestone lifecycle state")
    prerequisites: Tuple[VerifiedRoadmapPrerequisite, ...] = Field(default_factory=tuple, description="Prerequisite skills")
    learning_objectives: Tuple[str, ...] = Field(default_factory=tuple, description="Actionable learning competencies")
    resources: Tuple[VerifiedApprovedResource, ...] = Field(default_factory=tuple, description="Approved curated resources")
    project: Optional[VerifiedApprovedProject] = Field(None, description="Approved curated engineering challenge")
    latest_verification: Optional[VerifiedCandidateEvidenceItem] = Field(None, description="Latest verification record")

    # Validated Gemini Narrative facts
    phase_title: str = Field(..., max_length=120, description="Validated action phase title")
    personalized_rationale: str = Field(..., max_length=600, description="Validated personalized rationale")
    key_topics: Tuple[str, ...] = Field(default_factory=tuple, max_length=10, description="Validated key technical topics")
    expected_focus: Optional[str] = Field(None, max_length=400, description="Validated study focus summary")

    model_config = ConfigDict(frozen=True, extra="forbid")


class ValidatedTopSkillGap(BaseModel):
    """Authoritative top skill gap enriched with validated explanation."""
    skill_id: UUID = Field(..., description="Canonical skill UUID")
    skill_name: str = Field(..., description="Canonical skill name")
    canonical_slug: str = Field(..., description="Taxonomy lookup slug")
    category: Optional[str] = Field(None, description="Taxonomy category")
    gap_status: SkillGapClassification = Field(..., description="Authoritative gap status")
    priority_score: Optional[float] = Field(None, description="Deterministic priority score")
    priority_level: Optional[PriorityTierLevel] = Field(None, description="Deterministic priority tier")
    demand_score: Optional[float] = Field(None, description="Market demand score")
    growth_rate: Optional[float] = Field(None, description="Market growth rate")
    
    # Validated narrative (optional if Gemini omitted for this gap)
    why_it_matters: Optional[str] = Field(None, max_length=500, description="Validated explanation of gap importance")
    suggested_focus: Optional[str] = Field(None, max_length=400, description="Validated focus recommendation")

    model_config = ConfigDict(frozen=True, extra="forbid")


class ValidatedRoadmapPDFContent(BaseModel):
    """
    Root validated document ready for ReportLab rendering.
    All authoritative metrics and records are copied strictly from Phase 2.
    All narrative fields have passed Reference Integrity Validation.
    """
    schema_version: str = Field("v1.0", description="Contract schema version")
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Authoritative Phase 2 facts (immutable)
    roadmap_id: UUID = Field(..., description="Canonical CandidateRoadmap UUID")
    candidate: VerifiedCandidateProfile = Field(..., description="Candidate profile facts")
    readiness: VerifiedReadinessMetrics = Field(..., description="Deterministic readiness facts")
    target_role_title: str = Field(..., description="Target career role")
    location: str = Field("India", description="Target hiring market")
    total_milestones: int = Field(..., ge=0, description="Total milestone count")
    high_priority_count: int = Field(..., ge=0, description="High priority milestone count")
    medium_priority_count: int = Field(..., ge=0, description="Medium priority milestone count")
    low_priority_count: int = Field(..., ge=0, description="Low priority milestone count")
    transitive_prerequisite_count: int = Field(..., ge=0, description="Transitive prerequisite count")
    market_facts: Tuple[VerifiedMarketDemandFact, ...] = Field(default_factory=tuple, description="Authoritative market facts")
    verification_evidence: Tuple[VerifiedCandidateEvidenceItem, ...] = Field(default_factory=tuple, description="Authoritative candidate evidence")
    weekly_hours_recommendation: Optional[int] = Field(None, description="Strictly None (never fabricated)")
    verification_hash: str = Field(..., description="Deterministic SHA-256 verification hash")

    # Validated Gemini Narrative facts
    personalized_subtitle: str = Field(..., max_length=200, description="Candidate-tailored subtitle")
    executive_summary: str = Field(..., max_length=1000, description="Executive summary narrative")
    readiness_explanation: str = Field(..., max_length=600, description="Readiness context explanation")
    validated_top_gaps: Tuple[ValidatedTopSkillGap, ...] = Field(default_factory=tuple, description="Enriched top skill gaps")
    validated_phases: Tuple[ValidatedRoadmapPhase, ...] = Field(..., min_length=1, description="Enriched ordered phases")
    immediate_next_steps: Tuple[str, ...] = Field(..., min_length=1, max_length=10, description="Actionable next steps")
    closing_encouragement: str = Field(..., max_length=600, description="Closing encouragement narrative")

    model_config = ConfigDict(frozen=True, extra="forbid")
