"""
Deterministic prompt assembly for AI Roadmap Explanation.
Post-MVP Phase 4.

Enforces:
- Authoritative ground truth of the canonical roadmap.
- Strict prohibition against re-ordering, inventing skills, inventing URLs, or modifying priority facts.
"""

from typing import Dict, List, Optional
from app.ai.qwen.models import QwenMessage
from app.schemas.roadmap import CanonicalRoadmapData

ROADMAP_EXPLAINER_SYSTEM_PROMPT = (
    "You are an evidence-grounded career roadmap explainer and study coach for SkillForge AI.\n"
    "The supplied roadmap is authoritative, verified ground truth deterministically generated by SkillForge.\n"
    "Core boundary invariants:\n"
    "1. The LLM never decides what is true. The supplied roadmap milestones, sequence order, and priority tiers are ground truth.\n"
    "2. Never alter the milestone sequence, invent new skills, or change priority tiers.\n"
    "3. Never invent unapproved external URLs, websites, or bootcamps. Refer only to the approved resources and project deliverables present in the roadmap.\n"
    "4. Explain clearly why each milestone is placed in its specific sequence, emphasizing foundational prerequisites before dependent tools.\n"
    "5. Provide actionable, supportive study advice and milestone pacing for the candidate's target role."
)


def build_roadmap_explanation_messages(
    roadmap: CanonicalRoadmapData,
    user_query: Optional[str] = None,
) -> List[QwenMessage]:
    """
    Serializes a CanonicalRoadmapData object into a structured prompt context.
    """
    context_lines = [
        f"TARGET ROLE: {roadmap.target_role_title}",
        f"MARKET LOCATION: {roadmap.location}",
        f"TOTAL MILESTONES: {roadmap.total_milestones}",
        f"HIGH PRIORITY GAPS: {roadmap.high_priority_count}",
        f"MEDIUM PRIORITY GAPS: {roadmap.medium_priority_count}",
        f"LOW PRIORITY GAPS: {roadmap.low_priority_count}",
        f"FOUNDATIONAL PREREQUISITE MILESTONES: {roadmap.transitive_prerequisite_count}",
        "",
        "CANONICAL MILESTONE SEQUENCE (AUTHORITATIVE):",
    ]

    for m in roadmap.milestones:
        prereq_names = [f"{p.skill_name} ({p.dependency_type.value})" for p in m.prerequisites]
        prereq_str = ", ".join(prereq_names) if prereq_names else "None (Foundational)"
        prio_str = f"Priority: {m.priority_level} ({m.priority_score})" if m.priority_level else "Foundational Prerequisite (Prerequisite-driven)"
        
        res_titles = [f"'{r.title}' ({r.provider})" for r in m.resources[:2]]
        res_str = ", ".join(res_titles) if res_titles else "Curated official documentation"
        
        proj_str = f"Practical Project: '{m.project.title}'" if m.project else "Hands-on implementation exercise"

        context_lines.append(
            f"Milestone #{m.order_index}: {m.skill_name} [{m.gap_status}]\n"
            f"  - Category: {m.category or 'Core'}\n"
            f"  - Status Rationale: {m.reason}\n"
            f"  - Prioritization: {prio_str}\n"
            f"  - Prerequisites: {prereq_str}\n"
            f"  - Approved Learning Resources: {res_str}\n"
            f"  - Challenge: {proj_str}\n"
        )

    context_block = "\n".join(context_lines)

    user_instruction = (
        user_query.strip()
        if user_query and user_query.strip()
        else "Please summarize my personalized roadmap, explain why the milestones are ordered this way, and provide practical advice for tackling Milestone 1."
    )

    user_content = (
        f"VERIFIED ROADMAP GROUND TRUTH:\n"
        f"\"\"\"\n"
        f"{context_block}\n"
        f"\"\"\"\n\n"
        f"CANDIDATE REQUEST:\n{user_instruction}\n\n"
        f"Please provide an encouraging, evidence-grounded overview explaining the milestone sequence and study strategy."
    )

    return [
        QwenMessage(role="system", content=ROADMAP_EXPLAINER_SYSTEM_PROMPT),
        QwenMessage(role="user", content=user_content),
    ]
