"""
Public API schemas for SkillForge AI (Qwen).

Follows the repository's response envelope convention ({"data": ..., "meta": ...}).
Raw Ollama payloads are never exposed.
"""
from typing import List, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.qwen_ai.context import SkillForgeContext

MAX_USER_MESSAGE_CHARS = 4000
MAX_HISTORY_MESSAGE_CHARS = 8000
MAX_HISTORY_ITEMS = 50


class ChatMessage(BaseModel):
    """A prior conversation turn. System messages are not accepted from clients."""

    model_config = ConfigDict(extra="forbid")

    role: Literal["user", "assistant"]
    content: str = Field(min_length=1, max_length=MAX_HISTORY_MESSAGE_CHARS)

    @field_validator("content")
    @classmethod
    def not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("content cannot be blank")
        return value.strip()


class ChatRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    message: str = Field(min_length=1, max_length=MAX_USER_MESSAGE_CHARS, description="The user's question.")
    conversation_id: Optional[UUID] = Field(None, description="Client-held conversation id; generated if omitted.")
    conversation_history: List[ChatMessage] = Field(
        default_factory=list,
        max_length=MAX_HISTORY_ITEMS,
        description="Previous turns, oldest first. The server does not store history.",
    )
    context: Optional[SkillForgeContext] = Field(
        None, description="Facts from other SkillForge modules (skills, gaps, roadmap, evidence...)."
    )

    @field_validator("message")
    @classmethod
    def not_blank(cls, value: str) -> str:
        if not value.strip():
            raise ValueError("message cannot be blank")
        return value.strip()


class SourceReference(BaseModel):
    id: str = Field(description="Evidence id shown to the model, e.g. E1")
    source: str
    title: Optional[str] = None
    evidence_type: Optional[str] = None
    cited: bool = Field(description="Whether the answer cites this id inline, e.g. [E1]")


RecommendationOrigin = Literal["roadmap", "skill_gap_engine", "priority_skills", "missing_skills"]


class Recommendation(BaseModel):
    """A SkillForge-supplied priority, echoed deterministically. Never generated by Qwen."""

    rank: int
    skill: str
    priority: Optional[str] = None
    origin: RecommendationOrigin


class ChatAnswer(BaseModel):
    answer: str
    conversation_id: UUID
    grounded: bool = Field(description="True when SkillForge context was supplied to the model.")
    sources: List[SourceReference] = Field(default_factory=list)
    recommendations: List[Recommendation] = Field(default_factory=list)


class ChatMeta(BaseModel):
    model: str
    generated_at: str
    latency_ms: int
    context_sections: List[str] = Field(default_factory=list)
    context_truncated: bool = False
    history_messages_used: int = 0
    answer_truncated: bool = Field(False, description="True if generation hit the model's token limit.")


class ChatResponse(BaseModel):
    data: ChatAnswer
    meta: ChatMeta


class QwenHealthData(BaseModel):
    status: Literal["ok", "unavailable", "model_missing"]
    model: str
    runtime_reachable: bool
    model_available: bool


class QwenHealthResponse(BaseModel):
    data: QwenHealthData